#!/usr/bin/env node
const { program } = require("commander");

program.command("order", "Order some food");
program.command("pay", "Pay for your order");

program.action(() => {
  program.help();
});

program.parse(process.argv);
